quarkus:
  http:
    port: 41005

  couchbase:
    connection-string: ${COUCHBASE_URL}
    username: ${COUCHBASE_USERNAME}
    password: ${COUCHBASE_PASSWORD}

  devservices:
    enabled: false

couchbase:
  dmc:
    bucketName: ${COUCHBASE_DMC_BUCKET_NAME}
    bucketScope: ${COUCHBASE_DMC_BUCKET_SCOPE}
    bucketCollection: ${COUCHBASE_DMC_BUCKET_COLLECTION}
